### ISSUE TITLE
Cannot acces network

### ISSUE THREAD

**Issue by MBry0** [Buyukcaglar/UltimateRemote#1]
I'm tring to register my Ultimate64 in the android app, but all I get is Device scan failed.
Tried automatic scan deevices, scan specific ip range, manual register. The app could nmot access local network.
The ultimate64 and the smartphone are connected to the same network, I can ping both from my pc.
The app needs network access permissions, but there's no request for it, and I cannot grant them manually.

**Comment by Buyukcaglar** [comment]
That is strange. Even automatic scan and scan specific up range fails, you should be able to manually register your Ultimate device. Can you please share which Android version and device you are using? Will try to setup a similar emulator setting to reproduce the problem. Thanks.

**Comment by Buyukcaglar** [comment]
With manual register i get "could not communicate with ultimate device on (ip). API version failed."

This means your mobile device is unable to make requests to the Ultimate device via the IP address you presented. Can you please confirm that following;

1. Your Ultimate device is on firmware version 3.11
2. You can access Ultimate devices web interface from your phone's browser (by entering http://[ULTIMATE_DEVICE_IP]) you should see "Ultimate 64 HTTP Server" page from your phone

**Comment by jadflat** [comment]
I'm getting the same issue. Can't scan, can't add manually. When the app installed there were no permission requests for Wi-Fi access, not sure if this is related.
![Screenshot_20240217-143724](https://github.com/Buyukcaglar/UltimateRemote/assets/3272531/6241bc0a-ded6-47af-87da-ddc95c3fd12b)
![Screenshot_20240217-143705](https://github.com/Buyukcaglar/UltimateRemote/assets/3272531/6feba7d6-6c8f-4b40-9136-d18a46ee581d)


Android 14
Pixel 6

**Comment by MBry0** [comment]
> Can you please confirm that following;
> 
> 1. Your Ultimate device is on firmware version 3.11
> 2. You can access Ultimate devices web interface from your phone's browser (by entering http://[ULTIMATE_DEVICE_IP]) you should see "Ultimate 64 HTTP Server" page from your phone

1. Yes
2. Yes

**Comment by Buyukcaglar** [comment]
Investigating problem, will update as soon as possible

**Comment by Buyukcaglar** [comment]
@jadflat , @MBry0 found the problem, submitted a new build to Play Store, as soon as it relases, you may update to new version. The problem should be fixed by then. Thank you for tkaing time and sharing problems. I'll also notfiy from here when the nw version released.

![image](https://github.com/Buyukcaglar/UltimateRemote/assets/4595315/1f57373f-6074-4188-b58f-513336adea8f)

**Comment by Buyukcaglar** [comment]
@jadflat, @MBry0  new version is out, please update (or reinstall) app on your phone and share feedback about the issue. Thanks.

**Comment by jadflat** [comment]
It's working now, thank you

**Comment by Buyukcaglar** [comment]
@jadflat thank you for quick feedback, now closing this issue.

**Comment by MBry0** [comment]
Everything works. Thank you.
