### ISSUE TITLE
Question on Remote Connection

### ISSUE THREAD

**Issue by JDraugr** [Buyukcaglar/UltimateRemote#2]
Will we be able to place our d64/g64 images on a server or PC and remotely mount them to our U64 Elite's virtual drive 8 or 9 and run them remotely? I'd love to see such a feature so I wouldn't have to keep copies of all my disk images on 3 separate U64s that I have throughout my home. :)

**Comment by Buyukcaglar** [comment]
@JDraugr yes you can, as long as you can browse them when you open the file selector, any file reachable by app can be remotely mounted by simply selecting from the appropriate path.
